### ISSUE TITLE
Build Failing on Sourcemap Creation

### ISSUE THREAD

**Issue by gkchestertron** [ciena-frost/ember-frost-chart#43]
Build is failing (probably on some external dependency float) with the following message:
```
Build Canceled: Broccoli Builder ran into an error with `Concat` plugin. 💥
ENOENT: no such file or directory, open '/home/jfellman/dev/ember-frost-chart/A/tmp/source_map_concat-input_base_path-mo2Pw29D.tmp/vendor/d3-selection/d3-selection.js'
Error: ENOENT: no such file or directory, open '/home/jfellman/dev/ember-frost-chart/A/tmp/source_map_concat-input_base_path-mo2Pw29D.tmp/vendor/d3-selection/d3-selection.js'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at SourceMap.addFile (/home/jfellman/dev/ember-frost-chart/A/node_modules/fast-sourcemap-concat/lib/source-map.js:74:33)
    at /home/jfellman/dev/ember-frost-chart/A/node_modules/broccoli-concat/concat.js:200:16
    at Array.forEach (<anonymous>)
    at Concat.<anonymous> (/home/jfellman/dev/ember-frost-chart/A/node_modules/broccoli-concat/concat.js:198:24)
    at /home/jfellman/dev/ember-frost-chart/A/node_modules/fast-sourcemap-concat/lib/source-map.js:416:14
    at Promise (<anonymous>)
    at SourceMap.end (/home/jfellman/dev/ember-frost-chart/A/node_modules/fast-sourcemap-concat/lib/source-map.js:403:12)
    at Concat._doLegacyBuild (/home/jfellman/dev/ember-frost-chart/A/node_modules/broccoli-concat/concat.js:183:22)
```
Looks related to this issue: https://github.com/ember-cli/ember-cli/issues/2912, but that should have been fixed long ago.

**Comment by juwara0** [comment]
I notice that this PR: https://github.com/ef4/fast-sourcemap-concat/pull/44 was merged and version `1.2.4` was released 4 days ago for this issue: https://github.com/ef4/fast-sourcemap-concat/issues/47

I also found this issue which might be related to what we are seeing: https://github.com/ef4/fast-sourcemap-concat/issues/46

**Comment by gkchestertron** [comment]
Sourcemaps have been disabled, and should be re-enabled when this is fixed in the external dependencies.
